# Generated by Django 4.1.3 on 2022-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=15, verbose_name='Name')),
                ('address', models.TextField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'main',
            },
        ),
    ]
